name: Trigger Reusable Workflow

on:
  push:
    branches: [main]

jobs:
  update-content:
    uses: uptimestack/workflow-yml/.github/workflows/deploy.yml@main
    with:
      message: "Goodbye from the caller repo!"

