name: Test Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  update-html:
    runs-on: self-hosted  # Match this to your runner's actual label(s)

    steps:
      - name: Echo runner info
        run: |
          echo "Running on self-hosted runner: $RUNNER_NAME"
          echo "Workflow triggered successfully"

      - name: Update index.html
        run: |
          echo "Updating HTML file..."
          sed -i 's|<h1>.*</h1>|<h1>Hello from self-hosted rr!</h1>|' /home/subhan.asad/flask_app/templates/index.html


