name: Trigger Reusable Workflow

on:
  push:
    branches: [main]

jobs:
  update-content:
    echo "Connecting with workflow repo"
    uses: uptimestack/workflow-yml/.github/workflows/deploy.yml@main
    with:
      message: "Hello from the caller repo!"
