name: Main-PR

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        shell: bash
        run: |
          echo "Hello there from PR yml"
